name: sunftmobilev3
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  carousel_slider: ^4.1.1
  http: ^0.13.4
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  path_provider: ^2.0.14
  fl_chart: ^0.62.0
  cached_network_image: ^3.2.1
  collection: ^1.16.0
  intl: ^0.18.0
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.5
  web3dart: ^2.3.5
  walletconnect_dart: ^0.0.11
  slider_button:
    git: "https://github.com/da-nish/Slider-Button"
  dio: ^5.1.0
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/SUNFTImages/
    - assets/MetamaskLogo/
